name: Release Draft

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.22.2"

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build_apk:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode key.properties file
        env:
          ENCODED_STRING: ${{ secrets.ANDROID_KEY_PROPERTIES }}
        run: echo $ENCODED_STRING | base64 -di > android/key.properties

      - name: Decode android-keystore.jks file
        env:
          ENCODED_STRING: ${{ secrets.ANDROID_KEY_STORE }}
        run: mkdir secrets && echo $ENCODED_STRING | base64 -di > android/android-keystore.jks

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64

      - name: Move and Rename Apk
        env:
          APK_NAME: "Rpass-v${{ needs.build.outputs.version }}"
        run: |
          base_path=build/app/outputs/flutter-apk/
          apk_name=v${{ env:APK_NAME }}
          mkdir dist/apks -p
          rm -rf dist/apks/*
          cp $base_path/app-arm64-v8a-release.apk dist/apks/$apk_name-arm64-v8a.apk
          cp $base_path/app-armeabi-v7a-release.apk dist/apks/$apk_name-armeabi-v7a.apk
          cp $base_path/app-x86_64-release.apk dist/apks/$apk_name-x86_64.apk

  release:
    needs:
      - build
      - build_apk
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Draft release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/apks/*.apk
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag_name: v${{ needs.build.outputs.version }}



